# --- Sample dataset

# --- !Ups

insert into pais (nome, data_cadastro, data_alteracao) values ('Afghanistan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Albania', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Algeria', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Andorra', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Angola', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Anguilla', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Antarctica', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Antigua and Barbuda', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Argentina', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Armenia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Aruba', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Australia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Austria', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Azerbaijan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bahamas', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bahrain', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bangladesh', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Barbados', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Belarus', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Belgium', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Belize', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Benin', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bermuda', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bhutan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bolivia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Plurinational State of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bosnia and Herzegovina', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Botswana', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bouvet Island', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Brazil', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('British Indian Ocean Territory', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Brunei Darussalam', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Bulgaria', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Burkina Faso', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Burundi', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cambodia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cameroon', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Canada', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cape Verde', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cayman Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Central African Republic', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Chad', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Chile', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('China', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Christmas Island', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cocos (Keeling) Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Colombia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Comoros', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Congo', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Congo the Democratic Republic of the', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cook Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Costa Rica', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Croatia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cuba', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Cyprus', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Czech Republic', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Denmark', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Djibouti', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Dominica', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Dominican Republic', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Ecuador', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Egypt', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('El Salvador', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Equatorial Guinea', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Eritrea', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Estonia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Ethiopia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Falkland Islands (Malvinas)', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Faroe Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Fiji', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Finland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('France', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('French Guiana', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('French Polynesia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('French Southern Territories', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Gabon', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Gambia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Georgia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Germany', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Ghana', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Gibraltar', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Greece', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Greenland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Grenada', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Guadeloupe', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Guam', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Guatemala', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Guernsey', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Guinea', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('GuineaBissau', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Guyana', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Haiti', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Heard Island and McDonald Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Holy See (Vatican City State)', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Honduras', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Hong Kong', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Hungary', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Iceland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('India', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Indonesia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Iran Islamic Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Iraq', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Ireland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Isle of Man', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Israel', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Italy', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Jamaica', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Japan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Jersey', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Jordan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Kazakhstan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Kenya', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Kiribati', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Korea Democratic Peoples Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Korea Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Kuwait', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Kyrgyzstan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Lao Peoples Democratic Republic', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Latvia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Lebanon', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Lesotho', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Liberia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Libyan Arab Jamahiriya', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Liechtenstein', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Lithuania', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Luxembourg', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Macao', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Macedonia the former Yugoslav Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Madagascar', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Malawi', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Malaysia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Maldives', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mali', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Malta', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Marshall Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Martinique', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mauritania', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mauritius', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mayotte', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mexico', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Micronesia Federated States of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Moldova Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Monaco', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mongolia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Montenegro', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Montserrat', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Morocco', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Mozambique', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Myanmar', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Namibia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Nauru', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Nepal', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Netherlands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Netherlands Antilles', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('New Caledonia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('New Zealand', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Nicaragua', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Niger', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Nigeria', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Niue', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Norfolk Island', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Northern Mariana Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Norway', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Oman', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Pakistan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Palau', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Palestinian Territory Occupied', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Panama', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Papua New Guinea', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Paraguay', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Peru', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Philippines', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Pitcairn', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Poland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Portugal', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Puerto Rico', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Qatar', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Romania', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Russian Federation', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Rwanda', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saint Helena Ascension and Tristan da Cunha', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saint Kitts and Nevis', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saint Lucia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saint Martin (French part)', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saint Pierre and Miquelon', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saint Vincent and the Grenadines', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Samoa', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('San Marino', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Sao Tome and Principe', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Saudi Arabia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Senegal', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Serbia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Seychelles', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Sierra Leone', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Singapore', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Slovakia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Slovenia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Solomon Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Somalia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('South Africa', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('South Georgia and the South Sandwich Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Spain', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Sri Lanka', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Sudan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Suriname', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Svalbard and Jan Mayen', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Swaziland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Sweden', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Switzerland', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Syrian Arab Republic', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Taiwan Province of China', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Tajikistan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Tanzania United Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Thailand', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('TimorLeste', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Togo', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Tokelau', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Tonga', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Trinidad and Tobago', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Tunisia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Turkey', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Turkmenistan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Turks and Caicos Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Tuvalu', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Uganda', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Ukraine', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('United Arab Emirates', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('United Kingdom', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('United States', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('United States Minor Outlying Islands', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Uruguay', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Uzbekistan', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Vanuatu', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Venezuela Bolivarian Republic of', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Viet Nam', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Virgin Islands British', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Virgin Islands U.S.', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Wallis and Futuna', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Western Sahara', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Yemen', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Zambia', 'now', 'now');
insert into pais (nome, data_cadastro, data_alteracao) values ('Zimbabwe', 'now', 'now');

insert into usuario (nome, email, senha, papel, status, validado, data_cadastro, data_alteracao, ultimo_acesso)
values ('Haroldo Ramirez da Nóbrega', 'haroldo.nobrega@cibiogas.org', '$2a$10$nbLHwCCpkqWbkUZEDX3G5e3CRDJuqTPgVRRfaNduKRiBdN8jVu7ai', 'ADMINISTRADOR', TRUE, TRUE, 'now', 'now', 'now');
insert into usuario (nome, email, senha, papel, status, validado, data_cadastro, data_alteracao, ultimo_acesso)
values ('Administrador', 'administrador@cibiogas.org', '$2a$10$nbLHwCCpkqWbkUZEDX3G5e3CRDJuqTPgVRRfaNduKRiBdN8jVu7ai', 'ADMINISTRADOR', TRUE, TRUE, 'now', 'now', 'now');
insert into usuario (nome, email, senha, papel, status, validado, data_cadastro, data_alteracao, ultimo_acesso)
values ('Gerente', 'gerente@cibiogas.org', '$2a$10$nbLHwCCpkqWbkUZEDX3G5e3CRDJuqTPgVRRfaNduKRiBdN8jVu7ai', 'GERENTE', TRUE, TRUE, 'now', 'now', 'now');
insert into usuario (nome, email, senha, papel, status, validado, data_cadastro, data_alteracao, ultimo_acesso)
values ('Usuário', 'usuario@cibiogas.org', '$2a$10$nbLHwCCpkqWbkUZEDX3G5e3CRDJuqTPgVRRfaNduKRiBdN8jVu7ai', 'USUARIO', TRUE, TRUE, 'now', 'now', 'now');

insert into categoria (nome, data_cadastro, data_alteracao)
values ('Planos e Leis', 'now', 'now');
insert into categoria (nome, data_cadastro, data_alteracao)
values ('Regulação', 'now', 'now');

insert into evento (nome, data_inicio, data_fim, site, localidade, instituicao, data_cadastro, data_alteracao)
values ('Seminário Técnico sobre Geração Distribuída', 'now', 'now', 'https://www.abiogas.org.br/seminariotecnicogdbi', 'São Paulo SP', 'Associação Brasileira de Biogás e Biometano (Abiogás)', 'now', 'now');

insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('Abiogás', 'https://www.abiogas.org.br/', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('Embrapa', 'https://www.embrapa.br/', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('Spirit Desing', 'http://www.spiritdesign.com/pt', 79, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('Biomassa e Bioenergia', 'http://www.biomassabioenergia.com.br/', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('DVO', 'http://www.dvoinc.com/', 229, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('Cana Bioenergia', 'http://www.canalbioenergia.com.br/', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('ABRAGEL Associação Brasileira de Geração de Energia Limpa', 'http://www.abragel.org.br', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('ANEEL Agência Nacional de Energia Elétrica', 'http://www.aneel.gov.br', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('EPE Empresa de Pesquisa Energética', 'http://www.epe.gov.br', 30, 'now', 'now');
insert into site (titulo, url, pais_id, data_cadastro, data_alteracao)
values ('MME Ministério das Minas e Energia', 'http://www.mme.gov.br', 30, 'now', 'now');

insert into idioma (nome, data_cadastro, data_alteracao) values ('Português', 'now', 'now');
insert into idioma (nome, data_cadastro, data_alteracao) values ('Ingles', 'now', 'now');
insert into idioma (nome, data_cadastro, data_alteracao) values ('Espanhol', 'now', 'now');